name: Run ETL + dbt

on:
  schedule:
    - cron: '30 23 * 3-10 *'
  workflow_dispatch:

jobs:
  run_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Run ETL script
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > key.json
          export GOOGLE_APPLICATION_CREDENTIALS="key.json"
          python etl.py  # change to your script's actual name

      - name: Set up dbt
        uses: dbt-labs/dbt-action@v1
        with:
          dbt-version: 1.7.0

      - name: Run dbt models
        env:
          DBT_GOOGLE_PROJECT: upheld-momentum-463013-v7
          DBT_GOOGLE_KEYFILE_JSON: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          cd dbt_project
          dbt deps
          dbt seed
          dbt run --select staging
