# dbt_project.yml

name: youtube_pipeline
version: '1.0'

profile: default

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  youtube_pipeline:
    staging:
      +materialized: view
    marts:
      core:
        +materialized: table
      reporting:
        +materialized: table
