name: Youtube_trending_pipeline
version: '1.0'

profile: default

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"



models:
  Youtube_trending_pipeline:

    staging:
      +schema: staging_youtube
      +materialized: view

    prep:
      +schema: intermediate_youtube
      +materialized: ephemeral

    marts:
      core:
        +schema: core_youtube
        +materialized: table

    youtube_star_schema:
      +schema: core_youtube
      +materialized: table
      dimensions:
        +schema: core_youtube
        +materialized: table
      facts:
        +schema: core_youtube
        +materialized: table

