name: Youtube_trending_pipeline
version: '1.0'

profile: default

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  Youtube_trending_pipeline:
    staging:
      +materialized: table
    prep:
      +materialized: table
    marts:
      core:
        +materialized: table
    youtube_star_schema:
      +schema: star_schema
      +materialized: table
      dimensions:
        +materialized: table
      facts:
        +materialized: table




