version: 2

models:
  - name: dim_video_star
    description: "Dimension table for YouTube videos"
    columns:
      - name: video_id
        description: "Primary key video"
        tests:
          - unique
          - not_null

  - name: dim_category_star
    description: "Dimension table for video categories"
    columns:
      - name: category_id
        description: "Primary key category"
        tests:
          - unique
          - not_null

  - name: dim_channel_star
    description: "Dimension table for YouTube channels"
    columns:
      - name: channel_title
        description: "Primary key for channel"
        tests:
          - unique
          - not_null

  - name: fact_video_metrics
    description: "Fact table for daily video performance"
    columns:
      - name: video_id
        description: "Foreign key to dim_video"
        tests:
          - relationships:
              to: ref('dim_video_star')
              field: video_id
      - name: category_id
        description: "Foreign key to dim_category"
        tests:
          - relationships:
              to: ref('dim_category_star')
              field: category_id
      - name: channel_title
        description: "Foreign key to dim_channel"
        tests:
          - relationships:
              to: ref('dim_channel_star')
              field: channel_title
