version: 2

sources:
  - name: dbt_tdereli
    database: upheld-momentum-463013-v7
    tables:
      - name: stg_youtube_trending
      - name: channel_info_enriched


models:
  - name: dim_video_star
    description: "Dimension table for YouTube videos"
    columns:
      - name: video_id
        description: "Primary key video"
        tests:
          - unique

  - name: dim_category_star
    description: "Dimension table for video categories"
    columns:
      - name: category_id
        description: "Primary key category"
        tests:
          - unique


  - name: dim_channel_star
    description: "Dimension table for YouTube channels"
    columns:
      - name: channel_id
        description: "Primary key for channel"
        tests:
          - unique


  - name: fact_video_metrics
    description: "Fact table for daily video performance"
    columns:
      - name: video_id
        description: "Foreign key to dim_video"
        tests:
          - relationships:
              to: ref('dim_video_star')
              field: video_id
      - name: category_id
        description: "Foreign key to dim_category"
        tests:
          - relationships:
              to: ref('dim_category_star')
              field: category_id
      - name: channel_id
        description: "Foreign key to dim_channel"
        tests:
          - relationships:
              to: ref('dim_channel_star')
              field: channel_id
