version: 2

sources:
  - name: youtube_trending
    database: bigquery-public-data
    schema: youtube
    tables:
      - name: trending_videos
        description: "Public YouTube trending videos dataset"
