version: 2

models:
  - name: stg_youtube_trending
    description: "Staging model that cleans raw YouTube trending data from BigQuery"
    columns:
      - name: video_id
        description: "Unique identifier for the video"
      - name: title
        description: "Title of the video"
      - name: channel_title
        description: "Channel name"
      - name: view_count
        description: "Number of views"
      - name: like_count
        description: "Number of likes"
      - name: comment_count
        description: "Number of comments"
      - name: published_at
        description: "When the video was published"
      - name: duration_seconds
        description: "Length of the video in seconds"
