version: 2



sources:
  - name: youtube_source    
    database: upheld-momentum-463013-v7
    schema: dbt_tdereli     
    tables:
      - name: youtube_dataset_eu
        description: "Raw YouTube trending videos data imported from API"

  
