version: 2

sources:
  - name: youtube
    database: bigquery-public-data
    schema: youtube
    tables:
      - name: trending_videos
        description: "Public dataset of YouTube trending videos"


  
