version: 2

sources:
  - name: youtube_source
    database: upheld-momentum-463013-v7
    schema: dbt_tdereli
    tables:
      - name: youtube_trending_videos
        description: "Raw YouTube videos data loaded from Python script"
