name: Run ETL + dbt

on:
  schedule:
    - cron: '45 1 * * *'
  workflow_dispatch:


jobs:
  run_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: List repo files
        run: ls -la

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Create .env file
        run: echo "api_key=${{ secrets.YOUTUBE_API_KEY }}" > .env







      - name: Decode GCP credentials
        run: |
          echo "${{ secrets.GCP_CREDENTIALS_BASE64 }}" | base64 -d > key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$PWD/key.json" >> $GITHUB_ENV
          echo "DBT_GOOGLE_KEYFILE_JSON=$(cat key.json | jq -c .)" >> $GITHUB_ENV

      - name: Run ETL script
        run: python etl.py


      - name: Run dbt models
        env:
          DBT_GOOGLE_PROJECT: upheld-momentum-463013-v7
        run: |
          dbt deps --profiles-dir .dbt
          dbt seed --profiles-dir .dbt
          dbt run --profiles-dir .dbt --select staging

