name: Run ETL + dbt

on:
  schedule:
    - cron: '45 1 * * *'
  workflow_dispatch:


jobs:
  run_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: List repo files
        run: ls -la

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Create .env file
        run: echo "api_key=${{ secrets.YOUTUBE_API_KEY }}" > .env



      - name: Create GCP credentials file
        run: |
          if echo "${{ secrets.GCP_CREDENTIALS }}" | grep '\\n' > /dev/null; then
            echo "Detected \\n-escaped JSON. Decoding it..."
            echo "${{ secrets.GCP_CREDENTIALS }}" | sed 's/\\n/\n/g' > key.json
          else
            echo "Detected multiline JSON. Writing directly..."
            echo "${{ secrets.GCP_CREDENTIALS }}" > key.json
          fi



      - name: Run ETL script
        #env:
          #GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > key.json
          export GOOGLE_APPLICATION_CREDENTIALS="key.json"
          python etl.py 

      
      - name: Install dbt
        run: pip install dbt-bigquery==1.7.0


      - name: Run dbt models
        env:
           DBT_GOOGLE_PROJECT: upheld-momentum-463013-v7
           DBT_GOOGLE_KEYFILE_JSON: ${{ secrets.GCP_CREDENTIALS }}
        run: |
           dbt deps --profiles-dir .dbt
           dbt seed --profiles-dir .dbt
           dbt run --profiles-dir .dbt --select staging 

