name: Run ETL + dbt

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:


jobs:
  run_pipeline:
    runs-on: ubuntu-latest
    env:
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: List repo files
        run: ls -la

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt



      - name: Run ETL script
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > key.json
          export GOOGLE_APPLICATION_CREDENTIALS="key.json"
          python etl.py 

